chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add-user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user-detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit-user'),
    path('chat-admin/users/<str:uuid>/delete/', views.delete_room, name='delete-room'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('chat.urls')),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

account/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    # 1.50
    # Managers are priority
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

chat/models.py
from django.db import models
from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at', )

    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'
    CHOICES_STATUS = (
        (WAITING, 'waiting'),
        (ACTIVE, 'active'),
        (CLOSED, 'closed')
    )
    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at', )

    def __str__(self):
        return f'{self.client} - {self.uuid}'

chat/views.py
from django.contrib import messages
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_POST
from .models import Room
from django.contrib.auth.decorators import login_required
from account.models import User
from account.forms import AddUserForm, EditUserForm


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)
    return JsonResponse({
        'message': 'Room created'
    })


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users
    })


@login_required
def room(request, uuid):
    chat_room = Room.objects.get(uuid=uuid)

    if chat_room.status == Room.WAITING:
        chat_room.status = Room.ACTIVE
        chat_room.agent = request.user
        chat_room.save()

    return render(request, 'chat/room.html', {
        'room': chat_room
    })


@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()
    # Работа related_name
    # Получаем все комнаты, созданные пользователем
    return render(request, 'chat/user_detail.html', {
        'user': user,
        'rooms': rooms,
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete_room'):
        chat_room = Room.objects.get(uuid=uuid)
        chat_room.delete()
        messages.success(request, 'The room was successfully deleted')
        return redirect(reverse('chat:admin'))
    else:
        messages.error(request, "You don't have the rights to delete room")
        return redirect(reverse('chat:admin'))


@login_required
def edit_user(request, uuid):
    if request.user.has_perm('user.edit_user'):
        user = User.objects.get(pk=uuid)
        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)
            # instance=user - то, что будет уже в форме
            # request.POST - данные, которые были отправлены с формы
            if form.is_valid():
                form.save()
                messages.success(request, 'The changes have been saved!')
                return redirect(reverse('chat:admin'))
        else:
            form = EditUserForm(instance=user)
        # У нас крайне выгодное расположение return, ибо user общий, а
        # form приспосабливаться: если POST и невалидная форма, то вернёт форму с данными до отправки
        # Если же GET-запрос, то вернёт форму с данными из базы данных
        return render(request, 'chat/edit_user.html', {
            'user': user,
            'form': form
        })
    else:
        messages.error(request, "You don't have the rights to edit users")
        return redirect(reverse('chat:admin'))


@login_required
def add_user(request):
    if request.user.has_perm('user.add_user'):
        if request.method == "POST":
            form = AddUserForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.set_password(request.POST.get('password'))
                user.save()
                if user.role == User.MANAGER:
                    # Находим группу с именем
                    # Далее добавляем пользователя в группу, чтобы дать права
                    group = Group.objects.get(name='Managers')
                    group.user_set.add(user)
                messages.success(request, 'The user was added!')
                return redirect(reverse('chat:admin'))
        else:
            form = AddUserForm()
        return render(request, 'chat/add_user.html', {
            'form': form
        })
    else:
        messages.error(request, "You don't have the rights to add users")
        return redirect(reverse('chat:admin'))

chat/templates/chat/add_user.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">Add user</h1>

    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-6 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add user</button>
    </form>
{% endblock %}

chat/templates/chat/admin.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl">Chat admin</h1>

    {% if perms.user.add_user %}
<!--
Проверка на есть ли у текущего пользователя права на добавление новых пользователей в системе.
-->
    <div class="mt-8">
            <h2 class="mb-4 text-lg">Users</h2>
            {% csrf_token %}
            <a href="{% url 'chat:add-user' %}" class="inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add
                user</a>

            <div class="mt-6">
                {% for user in users %}
                    <div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' '' %}">
<!--                        Карусель. Серая строка, белая, серая, белая..
-->
                        <p class="px-2">
                            <a href="{% url 'chat:user-detail' user.pk %}">{{ user.name }}</a>
                        </p>

                        <p class="px-2">{{ user.email }}</p>

                        <p class="px-2">{{ user.get_role_display }}</p>
<!--
это метод модели Django, который возвращает отображаемое значение для поля-атрибута role для объекта user.
Метод get_role_display() доступен только для полей-атрибутов модели,
которые имеют параметр choices и служит для получения человекочитаемого значения для поля-атрибута с помощью его значения в choices.
-->

                        <p class="px-2 text-right">
                            {% if perms.user.edit_user %}
                                <a href="{% url 'chat:edit-user' user.pk %}" class="underline">Edit</a>
                            {% endif %}
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Rooms</h2>

        {% include 'chat/room_list.html' %}
<!--
Переменные, переданные в шаблон admin.html, также будут работать в шаблон, использованный в include
То есть rooms работает в room_list
-->
    </div>

{% endblock %}

chat/templates/chat/chat_bubble.html
<div id="chat" class="max-w-[300px] fixed right-2 bottom-2 p-4 bg-white border border-gray-300 rounded-xl">
    <div id="chat_icon">
        <button id="chat_open" class="w-[50px] flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="text-rose-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
            </svg>
        </button>
    </div>

    <div id="chat_welcome" class="hidden">
        <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Your name...">

        <button id="chat_join" class="py-2 px-6 rounded-xl text-white bg-rose-600">Join chat</button>
    </div>

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll">
            <p>Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>

        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    </div>
</div>

chat/templates/chat/edit_user.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">Edit user</h1>

    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-6 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Save Changes</button>
    </form>
{% endblock %}

chat/templates/chat/room.html
{% extends 'core/base.html' %}

{% load static %}

{% load chat_extras %}

{% block content %}
    <h1 class="text-2xl">Room «{{ room.uuid }}»</h1>

    <hr class="my-6">

    <p class="mb-6">
        <b>Name: </b>{{ room.client }}<br>
        <b>Started: </b>{{ room.created_at|timesince }} ago<br>
        <b>Status: </b>{{ room.get_status_display }}<br>
        <b>Page: </b>{{ room.url }}<br>
        <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}<br>
    </p>

    <hr class="mb-6">

    <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for message in room.messages.all %}
        <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
            {% if not message.created_by %}
            <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                {{ message.sent_by|initials }}
            </div>
            {% endif %}

            <div>
                <div class="p-4 rounded-xl {% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
                    <p class="text-sm">{{ message.body }}</p>
                </div>

                 <span class="text-xs text-gray-500 leading-none">{{ message.created_at|timesince }} ago</span>
            </div>
            {% if message.created_by %}
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                    {{ message.sent_by|initials }}
                </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    {% if room.status == 'active' %}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    {% endif %}
{% endblock %}


{% block scripts %}
    {% if room.status == 'active' %}
        {{ room.uuid|json_script:'room_uuid' }}
        {{ request.user.name|json_script:'user_name' }}
        {{ request.user.id|json_script:'user_id' }}
        <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock %}

chat/templates/chat/room_list.html
<div class="grid grid-cols-4 gap-4">
    {% for room in rooms %}
        <div class="p-4 rounded-xl {% if room.status == 'waiting' %}bg-emerald-100{% elif room.status == 'active' %}bg-yellow-100{% else %}bg-gray-100{% endif %}">
            <h3 class="mb-4 text-lg">Chat</h3>

            <p>
                <b>ID: </b>{{ room.uuid }}<br>
                <b>Name: </b>{{ room.client }}<br>
                <b>Status: </b>{{ room.get_status_display }}<br>
<!--
get_status_display() - это метод модели в Django,
который позволяет получить отображаемое значение для поля-атрибута status объекта.

Метод get_status_display() доступен только для полей-атрибутов модели,
которые имеют параметр choices. Он служит для получения человекочитаемого значения для поля-атрибута с помощью его значения в choices.
-->
                <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
<!--
room.agent.name является переменной, которая может содержать имя агента комнаты.
Если room.agent.name не определено или содержит ложное значение, то выводится строка 'None yet...'.
-->
            </p>

            <a href="{% url 'chat:room' room.uuid %}"
               class="mt-4 inline-block py-2 px-6 bg-emerald-800 text-white rounded-xl">
                Join</a>

            <a href="{% url 'chat:delete-room' room.uuid %}"
               class="mt-4 inline-block py-2 px-6 bg-rose-800 text-white rounded-xl">Delete
            </a>
        </div>
    {% endfor %}
</div>

chat/templates/chat/user_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl">{{ user.name }}</h1>


    <div class="mt-8">
        <h2 class="mb-4 text-lg">Rooms</h2>

        {% include 'chat/room_list.html' %}
    </div>
{% endblock %}